# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Weather' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'lottie-ios', '3.2.3'
  pod 'URLImage'
  # Pods for Weather

  target 'WeatherTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'ViewInspector'
  end

  target 'WeatherUITests' do
    # Pods for testing
  end

end
